const ActionTypes = {
    USERNAME: 'USERNAME',
    TODO: 'TODO',
    DELETETODO: 'DELETETODO',
    EDITTODO: 'EDITTODO',
    UPDATETODO: 'UPDATETODO',
    CANCEL: 'CANCEL',
    DELETEALLTODO : "DELETEALLTODO"

}

export default ActionTypes;
